version: '3.8'

services:
  snapshot:
    build:
      context: ${SNAPSHOT_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.snapshot
    ports:
      - 3002:3002
    env_file:
      - ${SNAPSHOT_REPO_PATH}/.env
      - ./envs/.env.snapshot
    environment:
      PORT: 3002
    volumes:
      - ${SNAPSHOT_REPO_PATH}:/app
      - /app/node_modules
    command: yarn run vite --port=3002 --host
    depends_on:
      - snapshot-hub
      - snapshot-relayer
      - score-api

  snapshot-hub:
    build:
      context: ${SNAPSHOT_HUB_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.snapshot-hub
    ports:
      - 3000:3000
    env_file:
      - ${SNAPSHOT_HUB_REPO_PATH}/.env
      - ./envs/.env.snapshot-hub
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${SNAPSHOT_HUB_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  keycard:
    build:
      context: ${KEYCARD_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.keycard
    ports:
      - 3005:3000
    env_file:
      - ${KEYCARD_REPO_PATH}/.env
      - ./envs/.env.keycard
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${KEYCARD_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  snapshot-sequencer:
    build:
      context: ${SNAPSHOT_SEQUENCER_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.snapshot-sequencer
    ports:
      - 3001:3000
    env_file:
      - ${SNAPSHOT_SEQUENCER_REPO_PATH}/.env
      - ./envs/.env.snapshot-sequencer
      - ./envs/.env.snapshot-sequencer.local
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${SNAPSHOT_SEQUENCER_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  score-api:
    build:
      context: ${SCORE_API_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.score-api
    ports:
      - 3003:3000
    env_file:
      - ${SCORE_API_REPO_PATH}/.env
      - ./envs/.env.score-api
    environment:
      PORT: 3000
    volumes:
      - ${SCORE_API_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      - redis

  snapshot-relayer:
    build:
      context: ${SNAPSHOT_RELAYER_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.snapshot-relayer
    ports:
      - 3004:3000
    env_file:
      - ${SNAPSHOT_RELAYER_REPO_PATH}/.env
      - ./envs/.env.snapshot-relayer
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${SNAPSHOT_RELAYER_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    
  envelop:
    build:
      context: ${ENVELOP_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.envelop
    ports:
      - 3006:3000
    env_file:
      - ${ENVELOP_REPO_PATH}/.env
      - ./envs/.env.envelop
      - ./envs/.env.envelop.local
    environment:
      PORT: 3000
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${ENVELOP_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  envelop-ui:
    build:
      context: ${ENVELOP_UI_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.envelop-ui
    ports:
      - 3007:3007
    env_file:
      - ${ENVELOP_UI_REPO_PATH}/.env
      - ./envs/.env.envelop-ui
    environment:
      PORT: 3007
    volumes:
      - ${ENVELOP_UI_REPO_PATH}:/app
      - /app/node_modules
    command: yarn run vite --port=3007 --host
    depends_on:
      - envelop

  snapshot-sidekick:
    build:
      context: ${SNAPSHOT_SIDEKICK_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.snapshot-sidekick
    ports:
      - 3008:3000
    env_file:
      - ${SNAPSHOT_SIDEKICK_REPO_PATH}/.env
      - ./envs/.env.snapshot-sidekick
      - ./envs/.env.snapshot-sidekick.local
    environment:
      PORT: 3000
    volumes:
      - ${SNAPSHOT_SIDEKICK_REPO_PATH}:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  brovider:
    build:
      context: ${BROVIDER_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.brovider
    ports:
      - 3009:3000
    env_file:
      - ${BROVIDER_REPO_PATH}/.env
      - ./envs/.env.brovider
    environment:
      PORT: 3000
    volumes:
      - ${BROVIDER_REPO_PATH}:/app
      - /app/node_modules
  
  pineapple:
    build:
      context: ${PINEAPPLE_REPO_PATH}
      dockerfile: ${PWD}/Dockerfiles/Dockerfile.pineapple
    ports:
      - 3010:3000
    env_file:
      - ${PINEAPPLE_REPO_PATH}/.env
      - ./envs/.env.pineapple
    environment:
      PORT: 3000
    volumes:
      - ${PINEAPPLE_REPO_PATH}:/app
      - /app/node_modules

  mysql:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/fixtures:/fixtures
      # schemas
      - ${SNAPSHOT_RELAYER_REPO_PATH}/src/schema.sql:/schemas/snapshot-relayer/schema.sql
      - ${SNAPSHOT_SEQUENCER_REPO_PATH}/src/helpers/schema.sql:/schemas/snapshot-sequencer/schema1.sql
      - ${SNAPSHOT_HUB_REPO_PATH}/src/helpers/schema.sql:/schemas/snapshot-sequencer/schema2.sql
      - ${KEYCARD_REPO_PATH}/src/helpers/schema.sql:/schemas/keycard/schema.sql
      - ${ENVELOP_REPO_PATH}/src/helpers/schema.sql:/schemas/envelop/schema.sql
      - ${SNAPSHOT_SIDEKICK_REPO_PATH}/src/helpers/schema.sql:/schemas/snapshot-sidekick/schema.sql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mysql:
    driver: local
  redis:
    driver: local
