FROM node:16-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile --network-timeout 1000000

COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["yarn", "run", "dev"]
