FROM node:18-alpine

WORKDIR /app

# Install dependencies for Cypress
RUN apk add --no-cache xvfb ttf-freefont chromium

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn run build

EXPOSE 8080

CMD ["yarn", "run", "dev"]
