FROM node:18-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY ui/package.json ./ui/package.json
COPY ui/yarn.lock ./ui/yarn.lock

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3008

CMD ["yarn", "run", "dev"]
