FROM node:18-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache git py3-pip python3 gcc g++ make

WORKDIR /app

COPY . .

RUN yarn install --network-timeout 1000000

ENV PORT=3000
EXPOSE 3000

CMD ["yarn", "run", "dev", "--host"]
